version: "3"

tasks:
  build-image:
    cmds:
      - docker build -t "podsec:latest" .
      - docker image prune -f
      - docker volume prune -f

  deploy-k8s:
    cmds:
      - kubectl apply -f "./k8s/resources.yml"

  undeploy-k8s:
    cmds:
      - kubectl delete -f "./k8s/resources.yml"

  run:
    env:
      WORKDIR_PATH: ./out
      NAMESPACES: redis,mongodb
      LOG_LEVEL: debug
      CACHE_TIME: 60
      SMTP_HOST: localhost
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "test@example.com"
      SMTP_TO: "test@example.com"
    cmds:
      - go run ./src

  run-dir:
    env:
      WORKDIR_PATH: ./out
      DIRECTORIES: podsec-monitor
      LOG_LEVEL: debug
      CACHE_TIME: 60
      SMTP_HOST: localhost
      SMTP_PORT: 1025
      SMTP_USER: ""
      SMTP_PASSWORD: ""
      SMTP_FROM: "test@example.com"
      SMTP_TO: "test@example.com"
    cmds:
      #- git clone https://github.com/sandrolain/podsec-monitor ./out/podsec-monitor
      - go run ./src

  mailpit:
    cmds:
      - docker run -d --restart unless-stopped --name=mailpit -p 8025:8025 -p 1025:1025 axllent/mailpit
