apiVersion: v1
kind: Namespace
metadata:
  name: tools
  labels:
    name: tools

---
apiVersion: v1
kind: ServiceAccount
metadata:
  namespace: tools
  name: podsec-account
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: podsec-role
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources:
      - pods
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: podsec-rolebinding
  namespace: tools
subjects:
  - kind: ServiceAccount
    name: podsec-account
    namespace: tools
roleRef:
  kind: ClusterRole
  name: podsec-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: tools
  name: podsec-pv
spec:
  capacity:
    storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  hostPath:
    path: /data/podsec-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  namespace: tools
  name: podsec-pvc
spec:
  accessModes:
    - ReadWriteOnce # Modalità di accesso, puoi scegliere tra ReadWriteOnce, ReadOnlyMany, ReadWriteMany
  resources:
    requests:
      storage: 5Gi # Dimensione del tuo volume
---
apiVersion: batch/v1
kind: CronJob
metadata:
  namespace: tools
  name: podsec-cronjob
spec:
  schedule: "0 * * * *"
  jobTemplate:
    spec:
      backoffLimit: 0
      template:
        spec:
          serviceAccountName: podsec-account
          containers:
            - name: podsec
              image: podsec:latest
              imagePullPolicy: Never
              volumeMounts:
                - name: podsec-volume
                  mountPath: /workdir
              env:
                - name: LOG_LEVEL
                  value: debug
                - name: WORKDIR_PATH
                  value: /workdir
                - name: NAMESPACES
                  value: mongodb
          restartPolicy: Never
          volumes:
            - name: podsec-volume
              persistentVolumeClaim:
                claimName: podsec-pvc
